# Generated by Django 5.0.6 on 2024-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_book_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='registraion_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Profileimage', models.ImageField(upload_to='Profile')),
            ],
        ),
    ]
