# Generated by Django 5.0.7 on 2024-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textapp', '0002_product_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_db',
            name='Profile_img1',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image'),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='Profile_img2',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image'),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='Profile_img3',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image'),
        ),
    ]
