# Generated by Django 5.0.7 on 2024-07-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email_Id', models.EmailField(blank=True, max_length=50, null=True)),
                ('Message', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
